apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
  name: FLASHTOOL
  description: >
    [The Petstore](http://petstore.example.com) is an example API used to showWDQDWQW
    features of the OpenAPI spec.

    - First item

    - Second item
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
  uid: a82b961a-471d-4cbb-82e3-9ae50be8213
  etag: 0222fd428b5434efd9ccf889aee201a8c751131
# relations:
#   - type: ownedBy
#     targetRef: group:default/team-c
#   - type: providesApi
#     targetRef: api:default/hello-world
#   - type: providesApi
#     targetRef: api:default/petstore
#   - type: providesApi
#     targetRef: api:default/streetlights
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  # providesApis:
  #   - hello-world
  #   - petstore
  #   - streetlights
